version: '3'

name: ccp-compose #NECCESSARY

services:
    ccp-api:
        image: rafaau/ccp-api:latest
        ports:
            - 5121:8080
        depends_on:
            - redis
        networks:
            - ccp-network
        environment:
            - Redis__ConnectionString=redis:6379
            - WebApp__Port=5069
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
        privileged: true

    ccp-web:
        image: rafaau/ccp-web:latest
        ports:
            - 5069:80
        depends_on:
            - ccp-api
        networks:
            - ccp-network
        environment:
            - UserToken=Profi123
            - AdminToken=Profi2137
            - AppName=ProfiAspire
            - WebAPI__Port=5121

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - ccp-network     

networks:
    ccp-network:
        driver: bridge
