//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContainerControlPanel.Web.Locales.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 dni temu.
        /// </summary>
        public static string _2DaysAgo {
            get {
                return ResourceManager.GetString("2DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcja.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz kontener....
        /// </summary>
        public static string ChooseContainer {
            get {
                return ResourceManager.GetString("ChooseContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz instrument.
        /// </summary>
        public static string ChooseInstrument {
            get {
                return ResourceManager.GetString("ChooseInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz zasób....
        /// </summary>
        public static string ChooseResource {
            get {
                return ResourceManager.GetString("ChooseResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz zasób, aby wyświetlić metryki.
        /// </summary>
        public static string ChooseResourceTo {
            get {
                return ResourceManager.GetString("ChooseResourceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz czas....
        /// </summary>
        public static string ChooseTimestamp {
            get {
                return ResourceManager.GetString("ChooseTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontener.
        /// </summary>
        public static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id kontenera.
        /// </summary>
        public static string ContainerId {
            get {
                return ResourceManager.GetString("ContainerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontenery.
        /// </summary>
        public static string Containers {
            get {
                return ResourceManager.GetString("Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utworzony.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dni.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to za pomocą Docker-Compose.
        /// </summary>
        public static string DockerCompose {
            get {
                return ResourceManager.GetString("DockerCompose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas trwania.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włącz kolory.
        /// </summary>
        public static string EnableColors {
            get {
                return ResourceManager.GetString("EnableColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmienne środowiskowe.
        /// </summary>
        public static string EnvironmentVariables {
            get {
                return ResourceManager.GetString("EnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przykłady.
        /// </summary>
        public static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to godzina.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to godzin.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to godziny.
        /// </summary>
        public static string Hours1 {
            get {
                return ResourceManager.GetString("Hours1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W jaki sposób chcesz.
        /// </summary>
        public static string HowDoYouWant {
            get {
                return ResourceManager.GetString("HowDoYouWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obraz.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko.
        /// </summary>
        public static string Just {
            get {
                return ResourceManager.GetString("Just", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logi.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metryki.
        /// </summary>
        public static string Metrics {
            get {
                return ResourceManager.GetString("Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minut.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Więcej.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wykryto żadnych kontenerów.
        /// </summary>
        public static string NoAliveContainers {
            get {
                return ResourceManager.GetString("NoAliveContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono logów dla podanych parametrów.
        /// </summary>
        public static string NoLogsFound {
            get {
                return ResourceManager.GetString("NoLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wykryto żadnych metryk.
        /// </summary>
        public static string NoMetricsFound {
            get {
                return ResourceManager.GetString("NoMetricsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono żadnych tras.
        /// </summary>
        public static string NoTracesFound {
            get {
                return ResourceManager.GetString("NoTracesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porty.
        /// </summary>
        public static string Ports {
            get {
                return ResourceManager.GetString("Ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeinstaluj obraz i.
        /// </summary>
        public static string ReinstallImageAnd {
            get {
                return ResourceManager.GetString("ReinstallImageAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Żądanie.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom ponownie.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uruchomić ponownie.
        /// </summary>
        public static string RestartInfinitive {
            get {
                return ResourceManager.GetString("RestartInfinitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko punkty końcowe.
        /// </summary>
        public static string RoutesOnly {
            get {
                return ResourceManager.GetString("RoutesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchomione.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Źródło.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uruchomić.
        /// </summary>
        public static string StartInfinitive {
            get {
                return ResourceManager.GetString("StartInfinitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znacznik czasu.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łączna liczba znalezionych wyników.
        /// </summary>
        public static string TotalNumberOfFoundTraces {
            get {
                return ResourceManager.GetString("TotalNumberOfFoundTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ślady.
        /// </summary>
        public static string Traces {
            get {
                return ResourceManager.GetString("Traces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetl szczegóły.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetl logi.
        /// </summary>
        public static string ViewLogs {
            get {
                return ResourceManager.GetString("ViewLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczoraj.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
